# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for the repo.
# @note runs manually or automatically when there is a release
# @date 8/13/25
# @author cyberreefguru
# (c) CRG Makes 2025
name: Aquarius-Current-Detector-Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-export-pcb:
    uses: crgmakes/kicad-extras/.github/workflows/crgm-ecad-release.yaml@main
    with:
      name: 'Aquarius Current Detector'
      repo-name: 'module-current-detector'
      file-name: 'current-module'