# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for the repo.
# @note runs manually or automatically when there is a release
# @date 8/13/25
# @author cyberreefguru
# (c) CRG Makes 2025
name: Aquarius-Current-Detector-Module-Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  manual:
    if: github.event_name != 'release'
    uses: crgmakes/kicad-extras/.github/workflows/aquarius-pcb-release.yaml@main
    with:
      repo-name: module-current-detector
      file-name: current-module
      aq-version: v0.0.0
      aq-hash: '000000'

  release:
    if: github.event_name == 'release'
    uses: crgmakes/kicad-extras/.github/workflows/aquarius-pcb-release.yaml@main
    with:
      repo-name: module-current-detector
      file-name: current-module
      aq-version: ${{ github.event.release.tag_name }}
      aq-hash: $(git rev-parse --short HEAD)